
Highcharts Export Server

https://github.com/highcharts/node-export-server

In order to use this application, Highcharts needs to be downloaded and 
embedded. A license is required to use Highcharts if you're a 
for-profit, commercial, outfit. 

The license can be viewed here: https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-6.0.pdf


IF THE DOWNLOAD FAILS:
----------------------

Are you behind a proxy?
See https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

Are you behind a company firewall?
Try running "npm config set strict-ssl=false" before installing
