/**
 * @overview This script is ran by GitHub Actions to compare the images
 * generated by the visual tests.
 *
 * It uses external libraries which are installed in the visual_tests.yml
 *
 * A command to run this test: `node tests/visual/_compare_images.js`
 */

import fs from 'fs';
import sharp from 'sharp';
import pixelmatch from 'pixelmatch';
import { PNG } from 'pngjs';

async function compareImages(image1Path, image2Path, diffPath) {
  const image1 = await sharp(image1Path).png().toBuffer();
  const image2 = await sharp(image2Path).png().toBuffer();

  const { width: width1, height: height1 } = await sharp(image1Path).metadata();
  const { width: width2, height: height2 } = await sharp(image2Path).metadata();

  if (width1 !== width2 || height1 !== height2) {
    throw new Error('Images have different dimensions');
  }

  const png1 = PNG.sync.read(image1);
  const png2 = PNG.sync.read(image2);

  const { width, height } = png1;
  const diff = new PNG({ width, height });

  const numDiffPixels = pixelmatch(
    png1.data,
    png2.data,
    diff.data,
    width,
    height,
    {
      threshold: 0.1
    }
  );

  fs.writeFileSync(diffPath, PNG.sync.write(diff));

  return numDiffPixels;
}

const image1Path = 'tests/visual/test_example/red_circle.png';
const image2Path = 'tests/visual/test_example/red_circle_edited.png';
const diffPath = 'tests/visual/test_example/generated_diff.png';

console.log(
  'Result of compareImages: ',
  compareImages(image1Path, image2Path, diffPath)
);
