name: Deploy Docker Image

on:
  workflow_call:
    inputs:
      version:
        description: "The version number"
        required: true
        type: string
      registry:
        description: "The Docker Registry"
        default: "ghcr.io"
        required: false
        type: string
      image_name:
        description: "The Docker image name"
        default: ${{ github.repository }}
        required: false
        type: string
      build_image:
        description: "The Docker Build Image (repository) to deploy"
        required: true
        type: string
      build_image_tag:
        description: "The Docker Build Image Tag to retag from"
        required: true
        type: string
      deploy_tag:
        description: "The target tag to deploy as"
        required: true
        type: string
      environment:
        description: "The GitHub environment to deploy to"
        required: true
        type: string
      platforms:
        description: "The platforms to deploy"
        required: false
        type: string
        default: linux/amd64,linux/arm64

    outputs:
      image:
        description: "The deployed image"
        value: ${{ jobs.deploy.outputs.image }}

jobs:
  deploy:
    name: ${{ inputs.environment && format('Deploy {0} Image', inputs.environment) || 'Deploy Image' }}
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
      attestations: write

    outputs:
      image: ${{ steps.output.outputs.image }}

    steps:
      - name: Deploy to ${{ inputs.environment }}
        uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ${{ inputs.registry }}
          repository: ${{ inputs.build_image }}
          target: ${{ inputs.build_image_tag }}
          tags: |
            ${{ inputs.deploy_tag }}

      - name: Store outputs
        id: output
        run: |
          echo "image=${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.deploy_tag }}" >> "$GITHUB_OUTPUT"
